HZShop/ViewModels/GamesListViewModel.cs
using HZShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HZShop.ViewModels
{
    public class GamesListViewModel
    {
        public IEnumerable<Game> allGames { get; set; }
        public string currentCategory { get; set; }
    }
}

HZShop/ViewModels/HomeViewModel.cs
using HZShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HZShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Game> favGames { get; set; }
    }
}

HZShop/ViewModels/ShopCartViewModel.cs
using HZShop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HZShop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; }
    }
}

HZShop/Controllers/GamesController.cs
using HZShop.Data.Interfaces;
using HZShop.Data.Models;
using HZShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HZShop.Conrollers
{
    public class GamesController : Controller
    {
        private readonly IAllGames allGames;
        private readonly IGamesCategory gamesCategory;


        public GamesController(IAllGames iAllGames, IGamesCategory iGamesCategory)
        {
            allGames = iAllGames;
            gamesCategory = iGamesCategory;

        }

        [Route("Games/List")]
        [Route("Games/List/{category}")]
        public ViewResult List( string category)
        {
            string _category = category;
            IEnumerable<Game> games = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                games = allGames.Games.OrderBy(i => i.id);
            }
            else
            {
                if(string.Equals("Shooter", category, StringComparison.OrdinalIgnoreCase))
                {
                    games = allGames.Games.Where(i => i.Category.id.Equals(4)).OrderBy(i => i.id);
                }
                else if(string.Equals("Strategy", category, StringComparison.OrdinalIgnoreCase))
                {
                    games = allGames.Games.Where(i => i.Category.id.Equals(1)).OrderBy(i => i.id);
                }
                else if (string.Equals("RPG", category, StringComparison.OrdinalIgnoreCase))
                {
                    games = allGames.Games.Where(i => i.Category.id.Equals(2)).OrderBy(i => i.id);
                }
                else if (string.Equals("Horror", category, StringComparison.OrdinalIgnoreCase))
                {
                    games = allGames.Games.Where(i => i.Category.id.Equals(3)).OrderBy(i => i.id);
                   
                }

                currCategory = _category;


            }
            var gameObj = new GamesListViewModel
            {
                allGames = games,
                currentCategory = currCategory
            };

            ViewBag.Title = "Games Page";

            return View(gameObj);
        }
    }
}

HZShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HZShop.Data.Interfaces;
using HZShop.Data.Models;
using HZShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HZShop.Conrollers
{
    public class HomeController : Controller
    {
        private readonly IAllGames _gameRep;


        public HomeController(IAllGames gameRep)
        {
            _gameRep = gameRep;
       
        }
        public ViewResult Index()
        {
            var homeGames = new HomeViewModel
            {
                favGames = _gameRep.getFavGames
            };
            return View(homeGames);
        }
/*        public IActionResult Index()
        {

            return View();
        }*/
    }
}

HZShop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HZShop.Data.Interfaces;
using HZShop.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace HZShop.Conrollers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;
        public OrderController(ShopCart shopCart, IAllOrders allOrders)
        {
            this.shopCart = shopCart;
            this.allOrders = allOrders;
        }
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listCartItems = shopCart.getShopItems();
            if(shopCart.listCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Корзина порожня");
            }
            if(ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complate");
            }
            return View(order);
        }

        public IActionResult Complate()
        {
            ViewBag.Message = "Замовленя успішно оброблено";
            return View();
        }
    }
}

HZShop/Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HZShop.Data.Interfaces;
using HZShop.Data.Models;
using HZShop.Data.Repository;
using HZShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HZShop.Conrollers
{
    public class ShopCartController : Controller
    {
        private readonly IAllGames _gameRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllGames gameRep, ShopCart shopCart)
        {
            _gameRep = gameRep;
            _shopCart = shopCart;
        }

        public IActionResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listCartItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _gameRep.Games.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

HZShop/Views/Games/List.cshtml
    <h1>Всі ігри:</h1>
    <h3>@Model.currentCategory</h3>
    <div class="row mt-5 mb-2" >
        @{
            foreach (Game game in Model.allGames)
            {
                @Html.Partial("AllGames", game)
            }
        }
    </div>

HZShop/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model HomeViewModel

<h1>Популярні ігри:</h1>

<div class="row mt-5 mb-2">
    @{
        foreach (Game game in Model.favGames)
        {
            @Html.Partial("AllGames", game)
        }
    }
</div>

HZShop/Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Оформлення замовлення</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="address"></label>
            <div class="col-md-5">
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Заввершити замовлення" />
    </form>
</div>

HZShop/Views/Order/Complate.cshtml
<h3>@ViewBag.Message</h3>

HZShop/Views/Shared/AllGames.cshtml
@model Game

<div class="col-lg-4">
    <img class="img-thumbnail img-fluid" src="@Model.img" alt="@Model.name" />
    <h2>@Model.name </h2>
    <p>@Model.shortDesc</p>
    <p>
        Ціна: @Model.price.ToString("c")
    </p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Додати в корзину</a></p>
</div>

HZShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li>
                        <a href="/" class="nav-link px-2 text-secondary">HZShop</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Index" class="nav-link px-2 text-white">Головна</a>
                    </li>
                    <li>
                        <a href="/Games/List" class="nav-link px-2 text-white">Ігри</a>
                    </li>
                    <li>
                        <a href="/Games/List/Strategy" class="nav-link px-2 text-white">Стратегії</a>
                    </li>
                    <li>
                        <a href="/Games/List/Shooter" class="nav-link px-2 text-white">Шутери</a>
                    </li>
                    <li>
                        <a href="/Games/List/Horror" class="nav-link px-2 text-white">Хорори</a>
                    </li>
                    <li>
                        <a href="/Games/List/RPG" class="nav-link px-2 text-white">RPG</a>
                    </li>
                    <li>
                        <a href="/ShopCart/" class="nav-link px-2 text-white">Корзина</a>
                    </li>
                </ul>
                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2">Login</button>
                    <button type="button" class="btn btn-warning">Sign-up</button>
                </div>
            </div>
        </div>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="bg-dark text-center text-white">
        <div class="container p-4">
            <section class="mb-4">
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-twitter"></i>
                </a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-google"></i>
                </a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-instagram"></i>
                </a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-linkedin-in"></i>
                </a>
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-github"> </i>
                </a>
            </section>
        </div>
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
    </footer>

    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

HZShop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container">
    @foreach(var el in Model.shopCart.listCartItems)
    {
        <div class="alert alert-warning mt-3">
            <strong>Гра:</strong> @el.Game.name<br />
            <strong>Ціна:</strong> @el.Game.price.ToString("c")
        </div>
    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Сплатити</a>

</div>